test/addons/e10s-content/lib/httpd.js
test/addons/e10s-content/lib/main.js
test/addons/e10s-content/lib/test-content-script.js
test/addons/unsafe-content-script/main.js
test/test-content-script.js

and add them the e10s-content test addon

bug 1116544 - switch remaining tests to new content/worker

---

test/test-context-menu@2.js

@erikvold I disabled the test that times out & I believe is causing other tests to fail as well.

Bug 1115419 - Disable failing test

---

lib/sdk/ui/button/action.js
lib/sdk/ui/button/contract.js
lib/sdk/ui/button/toggle.js
lib/sdk/ui/button/view.js
test/test-ui-action-button.js
test/test-ui-toggle-button.js

This PR is made on top of the badge's one, because it was already r+ and improves the button's tests.
But is not landed yet because it depends by a platform one, so the only commit to be review is the following: https://github.com/ZER0/addon-sdk/commit/f71e768992a537b4839c687173d13b740d7b1296

Bug 889465 - Buttons need GC tests

---

lib/sdk/preferences/service.js

This can land only after Bug 783829 is fixed.

Bug 1110457 - Update prefs implementation to use newer proxy API.

---

lib/toolkit/loader.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1098391

Bug 1098391 - Best effort to load SDK loader dependencies lazily

---

test/test-dev-panel.js

@erikvold  can you please take a look at this ?

Make sure tools created by tests are destroyed.

---

test/test-buffer.js

Bug 1125766 changed the errors thrown from TextEncoder.

Bug 1130801: Test for the updated error type for buffers.

---

lib/toolkit/loader.js
test/fixtures/loader/lazy/main.js
test/test-loader.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1012988

Bug 1012988 - Ensure that the loader doesn't force loader magic modules

---

CONTRIBUTING.md

I've added a bit more detail on where to get the SDK from, and made a few other updates.

fix up contributing.md

---

lib/sdk/content/l10n-html.js
test/addons/e10s-l10n/data/test-localization.html
test/addons/e10s-l10n/locale/en.properties
test/addons/e10s-l10n/main.js
test/addons/l10n/data/test-localization.html
test/addons/l10n/locale/en.properties
test/addons/l10n/main.js

https://bugzilla.mozilla.org/show_bug.cgi?id=824489

Bug 824489 - Localize whitelisted HTML element attributes

---

lib/sdk/lang/type.js
test/test-lang-type.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1147747

Bug 1147747 - Fix isArray fallback function and isArgument to return correct value.

---

.travis.yml
bin/jpm-test.js
bin/node-scripts/apply-patch.js
bin/node-scripts/args.js
bin/node-scripts/last-commit-msg.js
bin/node-scripts/test.addons.js
bin/node-scripts/test.examples.js
bin/node-scripts/test.modules.js
bin/node-scripts/utils.js
gulpfile.js

Bug 1159554 - Implement some commit message tags which will filter travis tests

---

examples/actor-repl/package.json
examples/debug-client/package.json
examples/reading-data/package.json
examples/theme/package.json
examples/toolbar-api/package.json
examples/ui-button-apis/package.json
lib/jetpack-id/package.json
package.json
python-lib/cuddlefish/templates.py
python-lib/cuddlefish/tests/bug-715340-files/pkg-1-pack/package.json
python-lib/cuddlefish/tests/bug-715340-files/pkg-2-unpack/package.json
python-lib/cuddlefish/tests/bug-715340-files/pkg-3-pack/package.json
python-lib/cuddlefish/tests/bug-906359-files/fullName/package.json
python-lib/cuddlefish/tests/bug-906359-files/none/package.json
python-lib/cuddlefish/tests/bug-906359-files/title/package.json
test/addons/e10s-content/package.json
test/addons/e10s-tabs/package.json
test/addons/e10s/package.json

package.json "MPL 2.0" to "MPL-2.0"

---

lib/sdk/request.js
test/test-request.js

Allow get modified URL in case of a redirection. Forwarded responseURL property of encapsulated xhr.

Bug 1161493 - responseURL get property for response object in sdk/request

---

test/test-weak-set.js

* combine gc() calls 4 -> 1
* remove unnecessary test loader usage
* assert every 0.25 secs while waiting for gc() to avoid intermittent timeouts

Bug 1163796 - Combine gc() calls in test-weak-set.js to reduce intermittent fails

---

bin/node-scripts/test.ini.js
bin/node-scripts/update-ini.js
gulpfile.js
test/jetpack-package.ini

Bug 1119600 - Build gulp command to test test/jetpack-package.ini is correct 

---

test/addons/places/lib/test-places-bookmarks.js
test/addons/places/lib/test-places-history.js

Bug 1146887 distinguish testSearchSort for history vs bookmarks and catch possible errors

---

test/test-panel.js

This reverts commit 455202325da596e9b5d7802115734a36eff1457c, reversing
changes made to 736dde2fe046086ab8a585f3441228bac1465687.

Revert "Merge pull request #2013 from erikvold/1171562"

---

test/test-test-utils.js

in testCleanUIWithOnlyExtraTab

Bug 1163408 and Bug 1160397 Uncaught "TypeError: tab is undefined" error

---

test/tabs/test-firefox-tabs.js

The bug seems to be fixed, I'm adding a unit test to prevent regressions and close the bug for good.

Bug 922956 - Add unit test to prevent regressions
