lib/sdk/test/harness.js

This stops the mochitest harness from counting a pass or fail multiple times.

Bug 1119931: Reset results on each call to runTests.

---

lib/sdk/content/worker-child.js
lib/sdk/content/worker.js
lib/sdk/page-mod.js
test/test-page-mod.js

Sends synthetic pageshow events when we missed the real ones and adds some tests to that effect. Note that due to self.port being asynchronous worker.on('pageshow') arrives before any messages from the worker script itself.

Bug 1124703: Send synthetic pageshow events when asynchronous message passing mean that we miss the real ones.

---

lib/sdk/panel.js
test/test-panel.js

To verify whether the patch worked, I followed the following steps:
1. Update tests only and change `if (packaging.isNative) {` to `if (packaging.isNative && false) {` because otherwise all panel tests would be skipped.
2. Ran `JPM_FIREFOX_BINARY=/usr/bin/firefox-nightly node ./bin/jpm-test.js --type modules --filter test-panel:contentScriptWhen=start`
3. Observed that the new test failed.
4. Apply the fix.
5. Repeat step 2.
6. Observe that the new test passes.
7. Remove the `&& false` modification at step 1 and submit the patch.
This patch fixes a regression caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1083391.

Bug 1128478 - sdk/panel's show/hide events not emitted if contentScriptWhen != 'ready'

---

test/test-context-menu@2.js

When Java and click to play are enabled a notification bar appears when this page loads which interrupts the attempt to open the context menu.

Bug 1131144: Disable Java before testing a page that includes an applet tag

---

lib/sdk/test/harness.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1133301

Bug 1133301 - Do not use non-standard flag argument of String.prototype.replace in addon-sdk/.

---

lib/sdk/windows/observer.js

This (combined with bug 1133141) cuts CPOW traffic out of simply requiring the windows module.

Bug 1133834: sdk/windows/observer should ignore events from child process windows.

---

lib/sdk/addon/runner.js

Until we can make l10n e10s safe we can at least disable this module in add-ons that don't have any l10n data.

Bug 1132753: Disable html localisation when the add-on has no l10n data.

---

lib/sdk/page-worker.js
test/test-page-worker.js

See http://stackoverflow.com/questions/28813605/firefox-addon-sdk-page-worker-regex/

bug 1138545 - should be able to pass in a bare regex to page-worker

---

lib/sdk/content/page-mod.js

This removes the remaining CPOW traffic from page-mod.

Bug 1139113: Use DOMDocElementInserted events rather than the observer service to detect new documents to page-mod.

---

lib/sdk/preferences/service.js

See [bug 1132522](https://bugzilla.mozilla.org/show_bug.cgi?id=1132522).
We definitely need this particular change. I'm about 95% sure this is the only one, since we won't be changing the behavior of legacy Proxy.create() proxies.

Bug 1132522 - Update proxy handlers in the Addon SDK for ES6 error handling

---

test/pagemod-test-helpers.js
test/test-page-worker.js

By using a different ID the test loader doesn't have any `baseURI` pref set in `sdk/self` and so `data.url` will use `prefixURI`.

Bug 1142330: Make child loaders user a unique ID so they don't inherit the preferences of the parent loader.

---

lib/sdk/remote/parent.js

The devtools loader injects a loader variable into every module so if you try to declare a const or var loader in your module it will throw an exception.

Bug 1142114: Rename loader to loaderModule to avoid conflicts with the devtools loader

---

test/addons/e10s-remote/main.js
test/addons/remote/main.js

The remote APIs see frames that come from other panels in the UI. My guess is that one of these is loading early in the test, we can ignore it though.

Bug 1142608: Only listen for tab frames attaching.

---

lib/sdk/content/sandbox.js
lib/sdk/remote/child.js
lib/sdk/remote/core.js
lib/sdk/remote/parent.js
test/addons/e10s-remote/main.js
test/addons/e10s-remote/remote-module.js
test/addons/remote/main.js
test/addons/remote/remote-module.js
test/test-page-mod.js

getTabForContentWindow doesn't work in the child process so we accidentally inject the SDK console into any page a page-mod applies to. This switches to using the remote APIs where possible instead.
This adds an API for detecting whether a module is loaded in a child loader or not. It uses that to make it impossible to load sdk/remote/parent or sdk/remote/child in the wrong loader for safety.

Bug 1141796: Don't inject the SDK console into pages loaded in tabs.

---

lib/sdk/io/fs.js

Not sure what this declaration is leftover from but it is unused and leaks.

Bug 1144446: Fix sdk/io/fs leak.

---

lib/sdk/ui/button/view.js

- Updated the sdk specific attribute to the new more generic `constrain-size`, to have the buttons that fits the toolbar and the panel.
Notice that without this PR the buttons will be broken in the next uplift. See bug 1153952.

Bug 1153952 - social buttons are too large

---

lib/dev/frame-script.js
lib/dev/panel.js
test/test-dev-panel.js

Depends on platform change attached here (https://bug1075490.bugzilla.mozilla.org/attachment.cgi?id=8546311)

Bug 1075490 - Fix devtools docking.

---

lib/sdk/url.js

This blocks landing a patch in bug 1158222, where I want to disallow this syntax. (It's against the ES6 spec)

Fix invalid method syntax used in URL constructor

---

lib/sdk/io/buffer.js
lib/sdk/panel/utils.js
lib/sdk/util/sequence.js

These syntaxes are invalid in ES6:
var v;
([v]) = [0]; // BAD way to assign v = 0
({v}) = { v: 0 }; // BAD way to assign v = 0
ES6 says that when destructuring assignment is used (or when a variable or variables are declared using a destructuring pattern), array/object patterns must not be parenthesized.
There's no reason at all to parenthesize array patterns (you can assign directly to an unparenthesized pattern), so this only rarely happens.  But some people have parenthesized object patterns, as a way to disambiguate them from normal JS block statements.  However, ES6 doesn't sanction such disambiguation attempts.  The right way to fix this is to parenthesize the entire assignment, not just the object pattern.
There are a few uses of this in the addon SDK, that need fixing before I can …

Stop parenthesizing array/object pattern destructuring assignment targets

---

test/test-simple-storage.js

This patch fixes some ambiguity in the code. Corresponding to [bug report #1219712](https://bugzilla.mozilla.org/show_bug.cgi?id=1219712).

Bug 1219712: fix syntax error in test
